# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1bfa13fb4e4c563825c32886aa87caf879d01cffc2aca99f64fad6c327ae879bcba739e30d73890126f37dba06c6351331840827fcb40fd9769e93929e74a38f

test:
  secret_key_base: 87f072af90bcb566ca5b0054a892c238d8e2f04b04948d90baeb73cb03671853299d541e26bce8a43cbbc4a5f8d46636cdf3ca313987c4a270d3e3fd043e429c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
