# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7477442fb0bf93b94eef78406fb9336ff85d11ae3f08ac3d0b75db92f1aa88f5262ff77a64149406d68411707cd0ca57102037b1dd66bc723e6e2d3559d7661

test:
  secret_key_base: 7f9c4193ea737ed1f23681b5dc768e90e8c99e27acea4a8a8733ad8d03a996ca3f0ba1ad820177bac3fcb3955efab22d6e0c8711a14d82c0a1913dcfb4711fdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
